export const API_REQUEST = "@API_REQUEST";
export const API_CLEAN_RECORD = "@API_CLEAN_RECORD";
export const API_RESPONSE = "@API_RESPONSE";
export const API_SET_RECORD_MANUAL = "@API_SET_RECORD_MANUAL";
export const API_UPDATE_RECORD_PROPERTY = "@API_UPDATE_RECORD_PROPERTY";